### PR TITLE
Update local.cf

### PR DESCRIPTION
**Pull request by twocoolbeans**
Line 105  
/usr/share/spamassassin/20_dnsbl_teest.cf 
should be
 /usr/share/spamassassin/20_dnsbl_test.cf

### CODE REVIEW

**Comment by iredmail** [comment]
Thanks for the help. @twocoolbeans :)

**Comment by twocoolbeans** [comment]
Thank you for your help. I am schnappi on your forum.

**Comment by iredmail** [comment]
Noted. But forgive me, it’s too hard to connect GitHub account name to forum name. :(

**Comment by twocoolbeans** [comment]
Doesn't matter. Point being you have helped me many more times.

**Comment by iredmail** [comment]
Glad to help. :)

**Pull request merged**
